### ISSUE TITLE
Allow to configure custom EntryPoint

### ISSUE THREAD

**Issue by Daskus1** [LikeTheSalad/android-buddy#4]
I am trying to instrument a rather large application written in Kotlin and ran into some problems with bytecode generated by the Kotlin compiler that is not valid for byte-buddy. For reference, the issue is very similar to this: https://github.com/raphw/byte-buddy/issues/764

The proposed solution is to disable validation using: `new ByteBuddy().with(TypeValidation.DISABLED)`.
But I did not find a way to register a custom `EntryPoint` or a custom `ByteBuddy` instance. It would be very helpful to expose an interface where a user can overwrite the configuration of `ByteBuddy`.

A possible solution might be to expose a new decorator `@EntryPoint`, allowing android-buddy to find the `EntryPoint` defined by the user, which might look like this:
```java
@EntryPoint
public class MyEntryPoint implements EntryPoint {

    @Override
    public ByteBuddy byteBuddy(ClassFileVersion classFileVersion) {
        return new ByteBuddy().with(TypeValidation.DISABLED);
    }

    @Override
    public DynamicType.Builder<?> transform(TypeDescription typeDescription, ByteBuddy byteBuddy, ClassFileLocator classFileLocator, MethodNameTransformer methodNameTransformer) {
        return byteBuddy.rebase(typeDescription, classFileLocator, methodNameTransformer);
    }
}

```
If such an `EntryPoint` is found, `android-buddy` could then use an instance of it, instead of the default EntryPoint (as currently done in https://github.com/LikeTheSalad/android-buddy/blob/4e9b0be746ec3a0ef9dd667e26405a4ab5d6ea89/android-buddy-plugin/src/main/java/com/likethesalad/android/common/utils/bytebuddy/ByteBuddyClassesInstantiator.kt#L46).

BTW awesome project :)

**Comment by LikeTheSalad** [comment]
Hi @Daskus1 

Many thanks for your feedback! - Also, thanks for sharing the solution to this issue as well. I see what you mean and, I think that in the case of adding support for custom EntryPoints, your solution looks really nice to implement.

However, there's a couple of concerns that I have with it, mostly because I try to keep a balance in this project that would make it easy to use, fast and flexible for both consumers and producers. And based on that, I was thinking about the possible use cases that could arise from supporting custom EntryPoints in order to measure the cost/benefits of it.
- On the flexible side, it would be awesome indeed. Users with some high knowledge of Byte Buddy could provide their own EntryPoint based on their needs.
- Regarding performance, I was thinking that maybe providing this option to all of the producers could cause some performance penalties, as it'd possible for each producer/library to provide their own EntryPoint, which would be used exclusively for that producer's transformations, as opposed to what it is now where a single instance is used to handle all transformations available from both the producer and consumer sides. By having different instances of byte buddy we'd have to run several iterations which will go through the same classpath over and over which, in the worst cases where there's a lot of libraries, could be quite painful to handle for consumers as they'd get some quite long compile times.
- On the same topic, then I considered the possibility of allowing only consumers to provide a custom EntryPoint, but then probably some producers would need custom instances of byte buddy, which could cause some awkward scenarios in which a user/consumer would need to apply custom configurations on their project in order to properly run a producer's transformations, which could in turn also cause some clashing with other producers that might require the consumer to do the same for them, possibly making the consumer to have troubles to implement several android-buddy libraries.
- On the easy to use case, if we sacrifice the performance by allowing each library to provide their own instance, we could keep the consumer's "easy to use" benefit. However, if we don't wan't to sacrifice the performance, then things could get hairier for consumers, which I don't think it's a good idea, especially because a lot of Android devs, probably the majority, don't like messing with Gradle 😅 so I'm weary that by making things a bit more complicated for users, they might end up dropping android-buddy as a solution to their needs. As well as it could happen if their build time gets really slow while using this plugin.

Also, in the end, considering that a lot of Android projects are using Kotlin, and considering that the way Kotlin works in general might clash with said validation, then I believe it'd make sense to disable this validation for everybody by adding it in the current instance as is, I don't think this should introduce any considerably risks, although I could confirm that with Rafael just to make sure.

Again, many thanks for your feedback. If you believe there could be several other use cases where a custom bytebuddy instance support would be necessary apart from this case we're discussing now, please let me know in order to analyze those and, if needed, try to figure out a way to address them without affecting the items I was mentioning.

**Comment by LikeTheSalad** [comment]
Hi @Daskus1, I think this should be sorted on the new version `1.1.0`. Please have a look when you have a chance 👍 

Cesar

**Comment by Daskus1** [comment]
Sorry for the late response. 
Your points make a lot of sense and I actually didn't even think about all those cases. Disabling validation by default sounds like a good solution. Regarding custom entry points, let's see if other use cases that require it will come up in future. In the meantime I think the solution you implemented is enough :)
I had a chance to test the new version and it works like a charm!

Thank you again!

**Comment by LikeTheSalad** [comment]
Awesome! Glad to hear it worked for your use case 👍 

I'll close this ticket then, please reopen it if you find any issues related to type validations.

Thanks again for your feedback!
Cesar
